require("@rails/ujs").start()
require("turbolinks").start()
require("@rails/activestorage").start()
require("channels")

require("jquery")
require("bootstrap")
require("chartkick")
require("chart.js")
toastr = require("toastr")
Tagify = require("@yaireo/tagify")

require("shared/sidebar")
require("view/dictionary")
require("view/ticket")
require("view/template")
require("view/daterangepicker")
